### ISSUE TITLE
TO DISCUSS - pořadatel: zakládá a spravuje festivaly, interprety a obsah, který je prezentován divákům a neregistrovaným návštěvníkům

### ISSUE THREAD

**Issue by unsortedhashsets** [x00Pavel/festival-IS#26]
1) create festival page 
2) different view for registered and unregistered managed by organizer...? WTF
3) статусы фестиваля 0 - шаблон 1 - публичный 2- отменен (по дефолту создается шаблон после клика на "опубликовать" удаление фестиваля невозможно -> только отмена c сохранением фестиваля в ДБ

**Comment by x00Pavel** [comment]
Must-have functionality is done in this [commit](db4fa1b737be61662504d3ca8bf25260b933abf2)
