### ISSUE TITLE
#26 -> Add tags to band

### ISSUE THREAD

**Issue by x00Pavel** [x00Pavel/festival-IS#47]
Create clickable icon, when the user can choose or add new tags. @fure0061  (DUPLICATES)

**Comment by x00Pavel** [comment]
Look at code forms.py -> BandForm

**Comment by x00Pavel** [comment]
Same thing for genre

**Comment by fure0061** [comment]
add html, normalize, and add tags, so the user can add some tags. Thank you. Festivals and band also
